site_name: Saúde Goiás
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: pt-BR
  palette:
    - scheme: slate
      toggle:
        icon: material/weather-sunny 
        name: Switch to dark mode
      primary: teal
      accent: purple
      
    - scheme: default 
      toggle:
        icon: material/weather-night
        name: Switch to light mode    
      primary: teal
      accent: lime
